name: Thorney theme

# Enter the URL of your votebot here. No trailing slash please!
# It will be something like https://my-votebot.herokuapp.com
votebot_url: https://votebot.example.com

exclude: ["vendor"]

#remote-theme: OpenEastleigh/thorney
markdown: kramdown
kramdown:
  auto_ids: true
baseurl: "/"

defaults:
-
  scope:
    path: ""
  values:
    layout: "root"
